### ISSUE TITLE
Documentation and Example(s)

### ISSUE THREAD

**Issue by carlolf** [jhulick/cups-java#2]
I just stumbled on to this cups library, after having seen the older project "Cups4J" before. As I understand, you are basing your code on "Cups4j" and did some things better. This is fine!

I do not have any experience using CUPS and Java, but now I've got a task to implement print jobs in a CUPS environment. Therefore, I'm asking myself: how can I do this?  Of course, using a library who implements all the inner mechanisms using CUPS.

So, looking upon this git project, I immediately recognized: no examples there. And looking into the java source code, I do miss a lot of Java Doc explaining classes and methods. Your README states "CupsService.java: handles print jobs management". I cannot find it?!

It would be a great thing for this public project if you could do something concerning my rants. Thank You!

**Comment by jhulick** [comment]
@carlolf the rants are very valid. I created this project for my own needs dealing with connections issues in IPP printers at a customer site, specifically how they were configured for security. If my memory is correct, the differences in this repo from the standard Cups4j is the additional classes in the ssl package, for handling certs, a bit of Auth header details, and how these are integrated with Apache HttpClient (see HttpPoster.java).  

As for an examples, I did not setup any. Simple usage, with a printer configured with basic auth, would be something like this:

`
URL url = new URL("http://127.0.0.1:631/ipp");
CupsClient client = new CupsClient(url, "userName");
 AuthInfo auth = new AuthInfo("test", "test");
File testFile = new File("print.txt");
InputStream stream = new FileInputStream(testFile);
CupsPrintJob cupsPrintJob = new CupsPrintJob(stream, "Test Doc Printing 1");
PrintRequestResult result = client.print(url, cupsPrintJob, auth);
`

**Comment by carlolf** [comment]
Ok, I understand. Having no experience with Cups and IPP, but needing to implement a print service using a Cups server, I was looking around for open source libs. And first found cups4j, and then your git project here. As cups4j is some years old and not further developed, I thought cups-java would be better.
So I tried to use the test class from cups4j with your library and saw, it is rather different. Porting the test class using cups-java was only possible looking into the code, and make some guesses. I finally was succesful, but some there incertanities remain. So I wrote this issue.

**Comment by jhulick** [comment]
Ok, great to hear that you were able to test this source successfully. I too had issues with the older Cups4j, and other java libs implementing IPP protocol... If you want to contribute a test case to this repo I'd be glad to accept a PR. When I have a little extra time I'll probably update this repo again - test cases, upgrade Apache HTTP client, and a few other things. Until then, it may not change much without collaboration.

**Comment by carlolf** [comment]
Hi @jhulick ,

I uploaded my test program in the attached zip file. Hope you can use it and make it available for other users.

[testcups.zip](https://github.com/jhulick/cups-java/files/1481541/testcups.zip)

**Comment by carlolf** [comment]
BTW: is cups-java available for gradle or maven builds in some repository? I built it myself and deployed it into our own artifactory.

**Comment by jhulick** [comment]
@carlolf yes, see the gradle build files in the root directory of this project.
